#!/bin/bash

cd "$(dirname "$0")/.."

cabal sandbox init
cabal sandbox add-source vendor/messagepack-haskell
cabal update
cabal install --enable-tests --only-dependencies -j
cabal configure --enable-tests
cabal build -j
