#!/bin/bash

cd "$(dirname "$0")/.."

git submodule update --init
cabal sandbox init
cabal sandbox add-source vendor/msgpack-haskell/msgpack
cabal update
cabal install --enable-tests --only-dependencies -j
cabal configure --enable-tests
cabal build -j
