#!/bin/bash

cd "$(dirname "$0")/.."

cabal sandbox init
cabal update
cabal install --enable-library-profiling --only-dependencies -j
cabal configure --enable-library-profiling --enable-executable-profiling
cabal build -j
